### ISSUE TITLE
with esp32

### ISSUE THREAD

**Issue by ankit993** [BareConductive/mpr121#15]
i can't use this library with esp32

**Comment by stefandz** [comment]
Hi Ankit

This library is specifically written to support our Touch Board product. It should be possible to adapt the library to work with other platforms, such as the ESP32, but we can't spend time and effort producing and testing this code since we do not sell products using this platform.

If you wish to make appropriate modifications and submit them as a pull request, we would be happy to include them in our library.

I am sorry that I cannot be of further assistance.

All the best

Stefan
